### ISSUE TITLE
update to IDE 1.6.x

### ISSUE THREAD

**Issue by boelle** [lincomatic/arduino-1.0.5-r2-at90usb1286#1]
Hi

could you help me update the hardware files for the printrboard so it will work with IDE 1.6.x ?

**Comment by lincomatic** [comment]
Sorry, it's too much work to keep up with their changes. There really isn't any advantage to upgrading your Arduino.. just use the older version.

**Comment by boelle** [comment]
Well the marlin firmware does not support the older version :-/
